[package]
name = "fft_verifier"
version = "0.1.0"
edition = "2024_07"
description = "FFT GKR proof verifier for Starknet"
publish = false

[dependencies]
starknet = ">=2.15.0"

[[target.starknet-contract]]
casm = true
